---
# Playbook: cleanup_all.yml
# Description: Cleans up all WarehousePG components, including data directories, users, packages, and configuration files.
# Usage: ansible-playbook -i test_inventory.yml cleanup_all.yml

- name: Cleanup WarehousePG Cluster
  hosts: all
  become: yes
  vars:
    whpg_data_directories:
      - /data/warehousepg
      - /data/warehousepg_mirrors
      - /data/warehousepg_segments
      - /data/warehousepg_coordinator
      - /data/warehousepg_standby
      - /data/coordinator
      - /data/primary
      - /data/mirror
    whpg_users:
      - gpadmin
      - postgres
    whpg_packages:
      - warehouse-pg-7
      - warehouse-pg-clients
      - whpg-backup
  tasks:
    - name: Check if warehousepg service exists
      ansible.builtin.command: systemctl status warehousepg
      register: service_check
      changed_when: false
      failed_when: false

    - name: Stop WarehousePG services
      ansible.builtin.service:
        name: warehousepg
        state: stopped
      when: service_check.rc == 0
      register: service_stop
      failed_when: false

    - name: Kill any remaining postgres processes
      ansible.builtin.shell: pkill -9 -u gpadmin postgres || true
      changed_when: false
      failed_when: false

    - name: Remove WarehousePG data directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ whpg_data_directories }}"
      register: dir_removal
      failed_when: false

    - name: Remove WarehousePG packages
      ansible.builtin.dnf:
        name: "{{ whpg_packages }}"
        state: absent
      register: package_removal
      failed_when: false

    - name: Remove EDB repository configuration
      ansible.builtin.file:
        path: /etc/yum.repos.d/enterprisedb-gpsupp.repo
        state: absent
      failed_when: false

    - name: Remove WarehousePG users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
        remove: yes
        force: yes
      loop: "{{ whpg_users }}"
      register: user_removal
      failed_when: false

    - name: Remove configuration files
      ansible.builtin.file:
        path: /etc/warehousepg
        state: absent
      failed_when: false

    - name: Remove greenplum installation directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/greenplum-db
        - /usr/local/greenplum-db-7.3.0-WHPG
      failed_when: false

    - name: Remove custom host entries
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "{{ item }}"
        state: absent
      loop:
        - '^.*warehousepg.*$'
        - '^.*whpg.*$'
        - '^.*-repl$'
      failed_when: false

    - name: Remove any leftover temporary files
      ansible.builtin.shell: rm -rf /tmp/.s.PGSQL* /tmp/warehousepg* /tmp/gp* 2>/dev/null || true
      changed_when: false
      failed_when: false

    - name: Display cleanup summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Cleanup Summary for {{ inventory_hostname }}"
          - "======================================================"
          - "Service stopped: {{ 'yes' if service_stop is defined and service_stop.changed | default(false) else 'N/A or already stopped' }}"
          - "Directories removed: {{ dir_removal.results | selectattr('changed', 'defined') | selectattr('changed') | list | length }}/{{ whpg_data_directories | length }}"
          - "Packages removed: {{ 'yes' if package_removal.changed | default(false) else 'N/A or already removed' }}"
          - "Users removed: {{ user_removal.results | selectattr('changed', 'defined') | selectattr('changed') | list | length }}/{{ whpg_users | length }}"
          - "======================================================"

    - name: Reboot hosts (optional)
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: whpg_reboot_after_cleanup | default(false)
