---
# WarehousePG DR Site Setup Playbook
# This playbook:
#   1. Configures OS settings on DR site hosts
#   2. Installs WarehousePG on DR site hosts
#   3. Creates storage directories on DR site hosts
#   4. Sets up replication from primary to DR site
#
# Usage:
#   ansible-playbook -i test_inventory.yml dr_setup.yml
#   ansible-playbook -i test_inventory.yml dr_setup.yml --tags standby  # Standby only
#   ansible-playbook -i test_inventory.yml dr_setup.yml --tags mirrors  # Mirrors only
#   ansible-playbook -i test_inventory.yml dr_setup.yml --tags install  # Installation only

# Phase 1: Configure OS on DR site hosts
- name: Configure Operating System on DR Site
  hosts: whpg_dr_site
  become: yes
  gather_facts: yes
  
  roles:
    - role: warehousepg-os-config
      tags: [os, install]

# Phase 2: Install WarehousePG on DR site hosts
- name: Install WarehousePG on DR Site
  hosts: whpg_dr_site
  become: yes
  gather_facts: yes
  
  vars:
    # EDB Repository Token (REQUIRED - update with your token)
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
  
  roles:
    - role: warehousepg-install
      tags: [install, packages]

# Phase 3: Setup storage on DR site hosts
- name: Setup Storage on DR Site
  hosts: whpg_dr_site
  become: yes
  gather_facts: yes
  
  vars:
    # Storage directories - should match primary site
    whpg_data_directories:
      - /data/primary/seg1
      - /data/primary/seg2
    whpg_mirror_data_directories:
      - /data/mirror/seg1
      - /data/mirror/seg2
    # Coordinator storage - used by storage role
    whpg_coordinator_storage: /data/coordinator
    # Force creation on DR site (fresh install)
    whpg_force_create: true
    # Enable directory creation flags
    whpg_create_coordinator_dirs: true
    whpg_create_primary_dirs: true
    whpg_create_mirror_dirs: true
  
  roles:
    - role: warehousepg-storage
      tags: [storage, install]

# Phase 3b: Update /etc/hosts on primary site with DR site aliases for replication
- name: Configure /etc/hosts on Primary Site for Cross-Site Replication
  hosts: whpg_primary_site
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update /etc/hosts with all site information
      include_role:
        name: warehousepg-install
        tasks_from: configure_hosts
      tags: [hosts, install]

# Phase 3c: Setup passwordless SSH between primary and DR sites
- name: Configure Cross-Site SSH for DR Replication
  hosts: whpg_primary_site:whpg_dr_site
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Setup passwordless SSH for gpadmin across all sites
      include_role:
        name: warehousepg-install
        tasks_from: passwordless_ssh
      tags: [ssh, install]

# Phase 4 removed: DR replication role no longer used
