---
# DR failover playbook removed because DR site support was dropped.

- name: Failover playbook deprecated
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Inform user
      ansible.builtin.debug:
        msg: "DR site support was removed; failover playbook is deprecated."
