---
# Quick Install Playbook: Complete WarehousePG Installation
# This playbook runs all steps in sequence for a quick deployment
#
# Usage:
#   ansible-playbook -i inventory.yml quick_install.yml
#   ansible-playbook -i test_inventory.yml quick_install.yml
#
# SSH Configuration:
#   Make sure ansible_user and ansible_ssh_private_key_file are set in your inventory
#   Example: ansible-playbook -i inventory.yml quick_install.yml -u rocky --private-key ~/.ssh/mykey.pem
#
# Variables:
#   edb_subscription_token: Your EDB subscription token (required)
#   whpg_enable_mirrors: Enable mirror segments (default: false)
#   whpg_use_dr_site_mirrors: Use DR site for mirrors (default: false)

- name: WarehousePG Complete Installation - Primary Site
  hosts: whpg_primary_site
  become: yes
  
  vars:
    # EDB Repository Token (REQUIRED - update with your token)
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
    
    # Storage configuration for single-disk setup
    # These paths will be created on your root filesystem
    whpg_storage_base: "/data"
    whpg_coordinator_storage: "/data/coordinator"
    whpg_primary_storage: "/data/primary"
    whpg_mirror_storage: "/data/mirror"
    whpg_force_create: true
    
    # Mirror configuration (optional)
    whpg_enable_mirrors: false
    whpg_use_dr_site_mirrors: false
  
  pre_tasks:
    - name: Display installation start
      ansible.builtin.debug:
        msg: 
          - "======================================================"
          - "Starting WarehousePG installation on {{ inventory_hostname }}"
          - "======================================================"
          - "Connecting as user: {{ ansible_user | default('not specified') }}"
          - "Groups: {{ group_names }}"
          - "Site: Primary"
          - "Mirrors enabled: {{ whpg_enable_mirrors }}"
          - "DR site mirrors: {{ whpg_use_dr_site_mirrors }}"
          - "======================================================"

    - name: Set the EDB subscription token fact
      set_fact:
        edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
        whpg_force_create: true

  roles:
    # Step 1: OS Configuration and Tuning
    - role: warehousepg-os-config
      tags: [os-config, config]
      
    # Step 2: Install WarehousePG packages
    - role: warehousepg-install
      vars:
        edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
      tags: [install, packages]
      
    # Step 3: Create storage directories
    - role: warehousepg-storage
      vars:
        # Pass segment data directories so storage role creates them
        whpg_data_directories:
          - "/data/primary/seg1"
          - "/data/primary/seg2"
        whpg_mirror_data_directories:
          - "/data/mirror/seg1"
          - "/data/mirror/seg2"
      tags: [storage]

  post_tasks:
    - name: Display primary site installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Primary site installation completed on {{ inventory_hostname }}"
          - "======================================================"
          - "OS configured: ✓"
          - "Packages installed: ✓"
          - "Storage created: ✓"
          - "======================================================"

# DR Site Installation (if using DR site mirrors)
- name: WarehousePG Installation - DR Site
  hosts: whpg_dr_site
  become: yes
  
  vars:
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
  
  pre_tasks:
    - name: Display DR site installation start
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Starting DR site installation on {{ inventory_hostname }}"
          - "======================================================"
      when: whpg_use_dr_site_mirrors | default(false)
  
  roles:
    # Install on DR site for mirror segments
    - role: warehousepg-os-config
      tags: [os-config, config]
      when: whpg_use_dr_site_mirrors | default(false)
      
    - role: warehousepg-install
      tags: [install, packages]
      when: whpg_use_dr_site_mirrors | default(false)
      
    - role: warehousepg-storage
      tags: [storage]
      when: whpg_use_dr_site_mirrors | default(false)
  
  post_tasks:
    - name: Display DR site installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "DR site installation completed on {{ inventory_hostname }}"
          - "======================================================"
      when: whpg_use_dr_site_mirrors | default(false)

# Cluster Initialization (runs only on coordinator)
- name: Initialize WarehousePG Cluster
  hosts: whpg_primary_coordinator
  become: yes
  
  vars:
    # Data directories for primary segments
    # For single-disk setup, use subdirectories under /data
    whpg_coordinator_directory: "/data/coordinator"
    whpg_data_directories:
      - "/data/primary/seg1"
      - "/data/primary/seg2"
    
    # Mirror directories (used if mirrors are enabled)
    whpg_mirror_data_directories:
      - "/data/mirror/seg1"
      - "/data/mirror/seg2"
    
    # Mirror configuration
    whpg_enable_mirrors: false
    whpg_use_dr_site_mirrors: false
    whpg_mirror_port_base: 7000
    whpg_mirror_mode: "spread"
    
    # Standby coordinator (optional)
    whpg_standby_coordinator_hostname: ""
    
    # Timezone
    whpg_timezone: "US/Pacific"
  
  pre_tasks:
    - name: Display initialization start
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Initializing WarehousePG cluster"
          - "======================================================"
          - "Coordinator: {{ inventory_hostname }}"
          - "Mirrors enabled: {{ whpg_enable_mirrors }}"
          - "DR site mirrors: {{ whpg_use_dr_site_mirrors }}"
          - "Timezone: {{ whpg_timezone }}"
          - "======================================================"
  
  roles:
    - role: warehousepg-init
      tags: [init, cluster-init]
  
  post_tasks:
    - name: Display complete installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "WarehousePG Installation Complete!"
          - "======================================================"
          - ""
          - "Cluster Status:"
          - "  ✓ OS configuration applied"
          - "  ✓ WarehousePG packages installed"
          - "  ✓ Storage directories created"
          - "  ✓ Cluster initialized and running"
          - ""
          - "Configuration:"
          - "  - Coordinator: {{ inventory_hostname }}"
          - "  - Segments: {{ groups['whpg_primary_segments'] | length }}"
          - "  - Mirrors: {{ 'Enabled (' + ('DR site' if whpg_use_dr_site_mirrors else 'Same site') + ')' if whpg_enable_mirrors else 'Disabled' }}"
          - "  - Timezone: {{ whpg_timezone }}"
          - ""
          - "Next Steps:"
          - "  1. Connect to database:"
          - "     ssh {{ ansible_user }}@{{ ansible_host }}"
          - "     sudo su - gpadmin"
          - "     psql -d gpadmin"
          - ""
          - "  2. Verify cluster status:"
          - "     gpstate -s"
          - ""
          - "  3. Check segment configuration:"
          - "     psql -c 'SELECT * FROM gp_segment_configuration;'"
          - ""
          - "  4. Configure pg_hba.conf for remote access"
          - "     vi $COORDINATOR_DATA_DIRECTORY/pg_hba.conf"
          - "     gpstop -u  # Reload configuration"
          - ""
          - "Configuration Files:"
          - "  - /home/gpadmin/gpconfigs/gpinitsystem_config"
          - "  - /home/gpadmin/gpconfigs/hostfile_gpinitsystem"
          - "{% if whpg_enable_mirrors and whpg_use_dr_site_mirrors %}  - /home/gpadmin/gpconfigs/hostfile_mirror_segments{% endif %}"
          - ""
          - "Logs:"
          - "  - /home/gpadmin/gpAdminLogs/"
          - ""
          - "======================================================"
      tags: [summary]
