
# 1. OS Config, Install, Storage (Primary Site)
- name: WarehousePG OS Config, Install, Storage (Primary Site)
  hosts: whpg_primary_site
  become: yes
  any_errors_fatal: true
  vars:
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
    whpg_storage_base: "/data"
    whpg_coordinator_storage: "/data/coordinator"
    whpg_primary_storage: "/data/primary"
    whpg_mirror_storage: "/data/mirror"
    whpg_force_create: true
    whpg_enable_mirrors: true
    whpg_use_dr_site_mirrors: false
    whpg_mirror_mode: "group"
    whpg_coordinator_standby_host: "{{ groups['whpg_primary_coordinator'][0] }}"
    whpg_coordinator_standby_data_directory: "/data/standby_coordinator/gpseg-1"
    whpg_coordinator_standby_port: 5433
  pre_tasks:
    - name: Display installation start
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Starting WarehousePG installation on {{ inventory_hostname }}"
          - "======================================================"
          - "Connecting as user: {{ ansible_user | default('not specified') }}"
          - "Groups: {{ group_names }}"
          - "Site: Primary"
          - "Mirrors enabled: {{ whpg_enable_mirrors }}"
          - "DR site mirrors: {{ whpg_use_dr_site_mirrors }}"
          - "======================================================"
    - name: Add the edb_subscription_token
      ansible.builtin.set_fact:
        edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"

  roles:
    - role: warehousepg-os-config
      tags: [os-config, config]
    - role: warehousepg-install
      vars:
        edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"
      tags: [install, packages]
    - role: warehousepg-storage
      vars:
        whpg_data_directories:
          - "/data/primary/seg1"
          - "/data/primary/seg2"
        whpg_mirror_data_directories:
          - "/data/mirror/seg1"
          - "/data/mirror/seg2"
      tags: [storage]
  post_tasks:
    - name: Display primary site installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Primary site installation completed on {{ inventory_hostname }}"
          - "======================================================"
          - "OS configured: ✓"
          - "Packages installed: ✓"
          - "Storage created: ✓"
          - "======================================================"


# 2. Cluster Initialization (Coordinator/Segments)
- name: Initialize WarehousePG Cluster (Coordinator/Segments)
  hosts: whpg_primary_coordinator
  become: yes
  any_errors_fatal: true
  vars:
    whpg_coordinator_directory: "/data/coordinator"
    whpg_data_directories:
      - "/data/primary/seg1"
      - "/data/primary/seg2"
    whpg_mirror_data_directories:
      - "/data/mirror/seg1"
      - "/data/mirror/seg2"
    whpg_enable_mirrors: true
    whpg_use_dr_site_mirrors: false
    whpg_mirror_port_base: 7000
    whpg_mirror_mode: "group"
    whpg_standby_coordinator_hostname: ""
    whpg_timezone: "US/Pacific"
  pre_tasks:
    - name: Display initialization start
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Initializing WarehousePG cluster"
          - "======================================================"
          - "Coordinator: {{ inventory_hostname }}"
          - "Mirrors enabled: {{ whpg_enable_mirrors }}"
          - "DR site mirrors: {{ whpg_use_dr_site_mirrors }}"
          - "Timezone: {{ whpg_timezone }}"
          - "======================================================"
  roles:
    - role: warehousepg-init
      tags: [init, cluster-init]
  post_tasks:
    - name: Display cluster initialization summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Cluster initialization completed on {{ inventory_hostname }}"
          - "======================================================"


# 3. Segment Mirrors (if enabled)
- name: Setup Segment Mirrors
  hosts: whpg_primary_site
  become: yes
  any_errors_fatal: true
  roles:
    - role: warehousepg-segment-mirrors
      tags: [mirrors]
      when: whpg_enable_mirrors | default(false)


# 4. Coordinator Standby (if configured)
- name: Setup Coordinator Standby
  hosts: whpg_coordinator_standby
  become: yes
  any_errors_fatal: true
  roles:
    - role: warehousepg-coordinator-standby
      tags: [coordinator-standby]
      when: whpg_coordinator_standby_host is defined and whpg_coordinator_standby_host != ''

 
- name: WarehousePG Installation - DR Site
  hosts: whpg_dr_site
  become: yes
  any_errors_fatal: true
  vars:
    edb_subscription_token: "{{ edb_subscription_token | default(lookup('env', 'EDB_SUBSCRIPTION_TOKEN')) }}"
  pre_tasks:
    - name: Display DR site installation start
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "Starting DR site installation on {{ inventory_hostname }}"
          - "======================================================"
      when: whpg_use_dr_site_mirrors | default(false)
  roles:
    - role: warehousepg-os-config
      tags: [os-config, config]
      when: whpg_use_dr_site_mirrors | default(false)
    - role: warehousepg-install
      vars:
        edb_subscription_token: "{{ edb_subscription_token | default(lookup('env', 'EDB_SUBSCRIPTION_TOKEN')) }}"
      tags: [install, packages]
      when: whpg_use_dr_site_mirrors | default(false)
    - role: warehousepg-storage
      tags: [storage]
      when: whpg_use_dr_site_mirrors | default(false)
  post_tasks:
    - name: Display DR site installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "DR site installation completed on {{ inventory_hostname }}"
          - "======================================================"
      when: whpg_use_dr_site_mirrors | default(false)

 
- name: Display Complete Installation Summary
  hosts: whpg_primary_coordinator
  gather_facts: no
  pre_tasks:
    - name: Ensure summary vars are defined
      ansible.builtin.set_fact:
        whpg_enable_mirrors: "{{ whpg_enable_mirrors | default(false) }}"
        whpg_use_dr_site_mirrors: "{{ whpg_use_dr_site_mirrors | default(false) }}"
        whpg_timezone: "US/Pacific"
  tasks:
    - name: Display complete installation summary
      ansible.builtin.debug:
        msg:
          - "======================================================"
          - "WarehousePG Installation Complete!"
          - "======================================================"
          - ""
          - "Cluster Status:"
          - "  ✓ OS configuration applied"
          - "  ✓ WarehousePG packages installed"
          - "  ✓ Storage directories created"
          - "  ✓ Cluster initialized and running"
          - ""
          - "Configuration:"
          - "  - Coordinator: {{ inventory_hostname }}"
          - "  - Segments: {{ groups['whpg_primary_segments'] | length }}"
          - "  - Mirrors: {{ 'Enabled (' + ('DR site' if whpg_use_dr_site_mirrors else 'Same site') + ')' if whpg_enable_mirrors else 'Disabled' }}"
          - "  - Timezone: {{ whpg_timezone }}"
          - ""
          - "Next Steps:"
          - "  1. Connect to database:"
          - "     ssh {{ ansible_user }}@{{ ansible_host }}"
          - "     sudo su - gpadmin"
          - "     psql -d gpadmin"
          - ""
          - "  2. Verify cluster status:"
          - "     gpstate -s"
          - ""
          - "  3. Check segment configuration:"
          - "     psql -c 'SELECT * FROM gp_segment_configuration;'"
          - ""
          - "  4. Configure pg_hba.conf for remote access"
          - "     vi $COORDINATOR_DATA_DIRECTORY/pg_hba.conf"
          - "     gpstop -u  # Reload configuration"
          - ""
          - "Configuration Files:"
          - "  - /home/gpadmin/gpconfigs/gpinitsystem_config"
          - "  - /home/gpadmin/gpconfigs/hostfile_gpinitsystem"
          - "{% if whpg_enable_mirrors and whpg_use_dr_site_mirrors %}  - /home/gpadmin/gpconfigs/hostfile_mirror_segments{% endif %}"
          - ""
          - "Logs:"
          - "  - /home/gpadmin/gpAdminLogs/"
          - ""
          - "======================================================"
      tags: [summary]
