---
# Main playbook for WarehousePG installation and configuration

- name: Install and Configure WarehousePG on Primary Coordinator
  hosts: whpg_primary_coordinator
  become: yes
  vars:
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"  # Replace with your actual token
    whpg_gpadmin_password: "NewPassword@123"
  roles:
    - warehousepg
  tags:
    - whpg_primary_coordinator

- name: Install and Configure WarehousePG on Primary Segments
  hosts: whpg_primary_segments
  become: yes
  vars:
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"  # Replace with your actual token
    whpg_gpadmin_password: "NewPassword@123"
  roles:
    - warehousepg
  tags:
    - whpg_primary_segments

- name: Install and Configure WarehousePG on DR Coordinator
  hosts: whpg_dr_coordinator
  become: yes
  vars:
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"  # Replace with your actual token
    whpg_gpadmin_password: "NewPassword@123"
  roles:
    - warehousepg
  tags:
    - whpg_dr_coordinator

- name: Install and Configure WarehousePG on DR Segments
  hosts: whpg_dr_segments
  become: yes
  vars:
    edb_subscription_token: "a42f0873c732be6edafe2e22849eb0ff"  # Replace with your actual token
    whpg_gpadmin_password: "NewPassword@123"
  roles:
    - warehousepg
  tags:
    - whpg_dr_segments
